from enum import StrEnum


class RoleName(StrEnum):
    OPERATOR = "OPERATOR"
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"


class SampleStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ACCESSIONED = "ACCESSIONED"
    IN_STORAGE = "IN_STORAGE"
    CHECKED_OUT = "CHECKED_OUT"
    QUARANTINED = "QUARANTINED"
    RELEASED = "RELEASED"
    DISPOSED = "DISPOSED"


class ManifestStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    VALIDATED = "VALIDATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    COMMITTED = "COMMITTED"


class IdentifierType(StrEnum):
    INTERNAL = "INTERNAL"
    EXTERNAL = "EXTERNAL"


class AliasType(StrEnum):
    BARCODE = "BARCODE"
    OTHER = "OTHER"


class StorageLocationType(StrEnum):
    SITE = "SITE"
    FREEZER = "FREEZER"
    RACK = "RACK"
    BOX = "BOX"
    POSITION = "POSITION"


class LineageRelationshipType(StrEnum):
    ALIQUOT = "ALIQUOT"
    DERIVATIVE = "DERIVATIVE"


class QuantityTransactionType(StrEnum):
    CONSUME = "CONSUME"
    PRODUCE = "PRODUCE"


class ExceptionStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ExceptionDisposition(StrEnum):
    RELEASE_TO_INVENTORY = "RELEASE_TO_INVENTORY"
    RELEASE_WITH_RESTRICTION = "RELEASE_WITH_RESTRICTION"
    DISPOSE = "DISPOSE"


class EnvironmentalEventType(StrEnum):
    TEMPERATURE_EXCURSION = "TEMPERATURE_EXCURSION"


class ShipmentStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ACCESSIONING = "ACCESSIONING"
    COMPLETE = "COMPLETE"


class AuditEventType(StrEnum):
    LOGIN = "LOGIN"
    MANIFEST_UPLOADED = "MANIFEST_UPLOADED"
    MANIFEST_VALIDATED = "MANIFEST_VALIDATED"
    MANIFEST_COMMITTED = "MANIFEST_COMMITTED"
    SHIPMENT_CREATED = "SHIPMENT_CREATED"
    SAMPLE_CREATED = "SAMPLE_CREATED"
    SAMPLE_ACCESSIONED = "SAMPLE_ACCESSIONED"
    LABEL_CREATED = "LABEL_CREATED"
    LABEL_REPRINTED = "LABEL_REPRINTED"
    CUSTODIAN_ASSIGNED = "CUSTODIAN_ASSIGNED"
    STORAGE_ASSIGNED = "STORAGE_ASSIGNED"
    SAMPLE_MOVED = "SAMPLE_MOVED"
    SAMPLE_CHECKED_OUT = "SAMPLE_CHECKED_OUT"
    SAMPLE_RETURNED = "SAMPLE_RETURNED"
    ALIQUOT_CREATED = "ALIQUOT_CREATED"
    DERIVATIVE_CREATED = "DERIVATIVE_CREATED"
    LINEAGE_CREATED = "LINEAGE_CREATED"
    LINEAGE_CYCLE_REJECTED = "LINEAGE_CYCLE_REJECTED"
    QUANTITY_CHANGED = "QUANTITY_CHANGED"
    TEMPERATURE_EXCURSION_RECORDED = "TEMPERATURE_EXCURSION_RECORDED"
    EXCEPTION_CREATED = "EXCEPTION_CREATED"
    SAMPLE_QUARANTINED = "SAMPLE_QUARANTINED"
    EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED"
    REPORT_GENERATED = "REPORT_GENERATED"
    USER_CREATED = "USER_CREATED"
    USER_DELETED = "USER_DELETED"


class QuantityUnit(StrEnum):
    ML = "mL"
    UL = "uL"
    MG = "mg"
    G = "g"


class ReportType(StrEnum):
    SAMPLE_HISTORY = "SAMPLE_HISTORY"
    INVENTORY = "INVENTORY"


ALLOWED_SAMPLE_TRANSITIONS: dict[SampleStatus, set[SampleStatus]] = {
    SampleStatus.RECEIVED: {SampleStatus.ACCESSIONED},
    SampleStatus.ACCESSIONED: {SampleStatus.IN_STORAGE},
    SampleStatus.IN_STORAGE: {
        SampleStatus.CHECKED_OUT,
        SampleStatus.QUARANTINED,
        SampleStatus.RELEASED,
        SampleStatus.DISPOSED,
    },
    SampleStatus.CHECKED_OUT: {SampleStatus.IN_STORAGE},
    SampleStatus.QUARANTINED: {
        SampleStatus.IN_STORAGE,
        SampleStatus.RELEASED,
        SampleStatus.DISPOSED,
    },
    SampleStatus.RELEASED: {SampleStatus.DISPOSED},
    SampleStatus.DISPOSED: set(),
}
